name: Publish
on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
         sudo apt install libfuse2 imagemagick
         export version=$(echo ${{ github.ref }} | cut -d '/' -f 3)
         echo ${{ github.ref }}
         echo $version
         sed -i -e 's/server/$version/g' Aria.yml
         ./build.sh
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: out/*.AppImage
